### ISSUE TITLE
Please create a git tag for versioning.

### ISSUE THREAD

**Issue by PertuyF** [LinearFold/LinearFold#4]
Dear @VincentZhangOR @LinearFold,

Thank you very much for the effort you put into developing LinearFold. I am willing to turn it into a conda package on Bioconda, that would facilitate distribution. The requirement for this is that you adopt some versioning strategy using a github release or a git tag.
Could you please do so?

Best,
Fabien

**Comment by LinearFold** [comment]
> Dear @VincentZhangOR @LinearFold,
> 
> Thank you very much for the effort you put into developing LinearFold. I am willing to turn it into a conda package on Bioconda, that would facilitate distribution. The requirement for this is that you adopt some versioning strategy using a github release or a git tag.
> Could you please do so?
> 
> Best,
> Fabien

**Comment by LinearFold** [comment]
Hell Fabien,

We've release a version with tag "LinearFold version 1.0". Thanks again for your interest. 

Best,
LinearFold Group
