### ISSUE TITLE
Web server not working

### ISSUE THREAD

**Issue by StefanZhang** [LinearFold/LinearFold#5]
Hello there, 
is the demo web server down at the moment? 

By running the linear fold using the defualt sequence, its responds "sorry, Something wrong dealing with the sequence"

**Comment by LinearFold** [comment]
Hello,

Thanks for your interest in our web server, and sorry for the inconvenience that you met.

The server is back online. Please have a try.

Thanks!

**Comment by StefanZhang** [comment]
> Hello,
> 
> Thanks for your interest in our web server, and sorry for the inconvenience that you met.
> 
> The server is back online. Please have a try.
> 
> Thanks!

Thanks for the quick help, does this web app have API that people can call and get dot sequence output? Or just the web app interface?
