### ISSUE TITLE
Batch input functionality?

### ISSUE THREAD

**Issue by StefanZhang** [LinearFold/LinearFold#6]
Hello there,

Is there an API that people could input multiple RNAs at once or using a loop?
So that we could compare the performance with other models using the same data set.

Many thanks!

**Comment by LinearFold** [comment]
Hello Stefan,

Our code do allow multiple input. You can save all sequences in an input_file line by line, and call LinearFold using the following command:

`cat input_file | ./LinearFold`

It will do all in one call.

Thanks!

**Comment by StefanZhang** [comment]
> 

Thanks you!
